### PR TITLE
Add CSS does HackNotts23

### PR DESCRIPTION
**Pull request by codemicro**

### CODE REVIEW

**Comment by LMBishop** [comment]
Is everyone in the photo fine with it being published publicly?

**Comment by codemicro** [comment]
oh plus i can confirm that i got consent from everyone pictured to put it on the site

**Comment by LMBishop** [comment]
Snap

**Review by LMBishop — APPROVED** [review]

**Comment by JTWWilson** [comment]
Fabulous picture! That page needs a bit of an update tbh but this is super useful.

**Comment by codemicro** [comment]
wheeeee

**Review by JTWWilson — APPROVED** [review]

**Pull request merged**
