### PR TITLE
Stop navbar wrapping

### LINKED ISSUE #263: Change the header bar to a clickable menu when the width is low
It might just be my personal opinion but when resizing the page, I don't see the point of transitioning from all the menu items being on the same line to having two lines and then to a clickable menu.
It would make more sense if we directly transitioned from a one line menu to a clickable menu.
Here are screenshots with screen width to support my idea
Is this something worth changing ?

### width > 870
Screenshot UoB Computer Science Society

### width <= 870
Screenshot UoB Computer Science Society

### width <= 600
Screenshot UoB Computer Science Society

### PR DESCRIPTION
**Pull request by RogerGabeller-ml**
this commit fixes #263

### CODE REVIEW

**Review by LMBishop — APPROVED** [review]
In future we may want to consider calculating this value rather than hard-coding it

**Review by MattyTheHacker — APPROVED** [review]
calculating would definitely be better I think but for the time being this is probably fine - potentially could be worth raising an issue to remind us.

**Comment by rainestormee** [comment]
I think we merge this as a temporary fix but then not close the existing issue?

**Comment by LMBishop** [comment]
I'll open a new issue for it

**Comment by LMBishop** [comment]
(P.S. George, your git settings on your machine aren't properly configured so you might not receive contribution credit properly)

**Pull request merged**
