### PR TITLE
Removed old event links, added Christmas meal link

### PR DESCRIPTION
**Pull request by LikkanChung**

### CODE REVIEW

**Comment by jedevc** [comment]
Hey, can you rebase onto master? There's merge conflicts that need to be resolved manually it looks like.

**Comment by LikkanChung** [comment]
Which conflicts? I _think_ I have already resolved them in the commits in this PR

**Comment by jedevc** [comment]
Did you pull from the upstream master?

**Comment by LikkanChung** [comment]
Yes

**Comment by jedevc** [comment]
Right, I've merged it manually.

**Pull request closed without merging**
