### PR TITLE
Update about

### PR DESCRIPTION
**Pull request by gsbaker**

### CODE REVIEW

**Comment by LikkanChung** [comment]
Please attach a screenshot of what it will look like here. And also select somebody to be a reviewer.

**Comment by gsbaker** [comment]
> Please attach a screenshot of what it will look like here. And also select somebody to be a reviewer.

Screenshot 2020-10-21 at 13 27 57

**Comment by gsbaker** [comment]
> > Please attach a screenshot of what it will look like here. And also select somebody to be a reviewer.
> 
> Screenshot 2020-10-21 at 13 27 57

The design and content has been reviewed already by the committee and further review by Jacqui and Jake.

**Review by JKHenes — APPROVED** [review]
Looked it over before, looks good :)

**Review by jedevc — APPROVED** [review]
Looks fairly ok, I like the new style. I do think it looks quite inconsistent with the rest of everything else, but in the long term we'll hopefully get that sorted.

On mobile the buttons collapse weirdly:
Screenshot from 2020-10-21 13-33-06
Screenshot from 2020-10-21 13-33-12

Why has the constitution been added in this diff?

**Comment by gsbaker** [comment]
> Looks fairly ok, I like the new style. I do think it looks quite inconsistent with the rest of everything else, but in the long term we'll hopefully get that sorted.
> 
> On mobile the buttons collapse weirdly:
> Screenshot from 2020-10-21 13-33-06
> Screenshot from 2020-10-21 13-33-12
> 
> Why has the constitution been added in this diff?

Just so that people can view the constitution as a PDF as well as the existing Google Doc. 

That's definitely an issue with padding! Thanks for finding that.

If I make another commit fixing it, can it be automatically added to this PR before I merge?

**Pull request merged**
