### PR TITLE
Add new committee

### PR DESCRIPTION
**Pull request by sapphyree**
Adds the new committee members (Marcus, Charlie) to the /committee page and updates Sofia's profile picture. Finally, removes Matty's Industrial Liaison role.

### CODE REVIEW

**Review by MattyTheHacker — APPROVED** [review]

**Review by JTWWilson — CHANGES_REQUESTED** [review]
Charlie's picture has some black padding on the sides, I think it just needs a moment in GIMP to crop it to 1x1

**Review by JTWWilson — APPROVED** [review]
Fixed :) Tbh quite a few of our pictures are a bit low quality but ah well

**Review by LMBishop — APPROVED** [review]

**Comment by LMBishop** [comment]
> Tbh quite a few of our pictures are a bit low quality but ah well

COuld be worth changing the convert script from 150x150 to something else and rescaling the images, given we don't apply this 'bandwith-saving' measure anywhere else on the site ([/clubs](https://cssbham.com/clubs))

**Comment by JTWWilson** [comment]
Agreed tbh. I don't quite understand the reason for it other than making it easier to clone the repo?

**Comment by MattyTheHacker** [comment]
> Agreed tbh. I don't quite understand the reason for it other than making it easier to clone the repo?

make an issue xoxo

**Pull request merged**
