### PR TITLE
Add membership statistics page

### LINKED ISSUE #458: Setup page to display membership statistics

### PR DESCRIPTION
**Pull request by MattyTheHacker**
closes #458

### CODE REVIEW

**Comment by MattyTheHacker** [comment]
just doing this so I can use the preview lmao pls don't merge

**Comment by MattyTheHacker** [comment]
can someone run prettier on this pls

**Comment by FrozenDude101** [comment]
There should be a way to get to the stats page, probably from /Members, but otherwise looks good.

**Comment by MattyTheHacker** [comment]
> There should be a way to get to the stats page, probably from /Members, but otherwise looks good.

Yeah agree - currently just trying to make the graphs a bit bigger but will look into doing that later

**Comment by MattyTheHacker** [comment]
okay happy for this to be properly reviewed to be merged now.

**Review by FrozenDude101 — COMMENTED** [review]
Can you make these consistent?
(L19, membership.md) / (L10, membership-stats.md)
`Check them out [here](/membership-stats)!`
`## What is Membership? Find out here: [Membership](/membership)`

**Comment by codemicro** [comment]
Is there any reason that the stats page isn't using the same white background as other pages, like `/membership`?

**Comment by MattyTheHacker** [comment]
> Can you make these consistent? (L19, membership.md) / (L10, membership-stats.md) `Check them out [here](/membership-stats)!` `## What is Membership? Find out here: [Membership](/membership)`

which would we prefer?

**Review by codemicro — COMMENTED** [review]
Is there any reason that the stats page isn't using the same white background as other pages, like `/membership`?

**Comment by codemicro** [comment]
> > Can you make these consistent? (L19, membership.md) / (L10, membership-stats.md) `Check them out [here](/membership-stats)!` `## What is Membership? Find out here: [Membership](/membership)`
> 
> which would we prefer?

I think the former flows and looks better, personally

**Comment by FrozenDude101** [comment]
> which would we prefer?
I think `[here](...)` looks cleaner.

**Comment by MattyTheHacker** [comment]
> Is there any reason that the stats page isn't using the same white background as other pages, like `/membership`?

that template is for text pages, as the content on this page is 90% charts I didn't think it appropriate to use that page type. This one also allows the charts to be much bigger than the other one.

**Review by codemicro — CHANGES_REQUESTED** [review]
I think a new template should probably be made to support this new page as the lack of a white background breaks the themeing of the rest of the site and make the page looks unfinished.

**Comment by MattyTheHacker** [comment]
>

**Comment by MattyTheHacker** [comment]
> I think a new template should probably be made to support this new page as the lack of a white background breaks the themeing of the rest of the site and make the page looks unfinished.

open an issue :)

**Review by codemicro — APPROVED** [review]

**Pull request merged**
