### PR TITLE
Add EPS Community graphic to about page

### PR DESCRIPTION
**Pull request by LMBishop**
Looks like this:

### CODE REVIEW

**Review by MattyTheHacker — APPROVED** [review]
looks good to me

**Comment by rainestormee** [comment]
Seems a bit low res to me
6565EFF2-3956-48DB-B309-80163B0FC72A
It’s probably better not to post the screenshot so people are forced to use the netlify link so we can catch a wider variety of platforms

**Comment by LMBishop** [comment]
> Seems a bit low res to me

It's 280 x something, I'm not sure where I can find a higher resolution graphic since it's straight from the uni website

Although at the same time, we use 150x150 for our committee photos sooo

**Comment by sapphyree** [comment]
> Seems a bit low res to me 6565EFF2-3956-48DB-B309-80163B0FC72A It’s probably better not to post the screenshot so people are forced to use the netlify link so we can catch a wider variety of platforms

Good point, I didn't actually see how low-res it was. While it looks *fine* on desktop, it really doesn't on mobile. Is there another image file we have that's better quality?

**Review by MattyTheHacker — APPROVED** [review]

**Review by rainestormee — APPROVED** [review]
lgtm

**Pull request merged**
