### PR TITLE
Update membership process details

### LINKED ISSUE #448: Membership page soon to be out of date
https://cssbham.com/membership will need to be updated at some point when we have a concrete idea of external members for the coming year. On hold until the policy has actually been written.

I'll update the below link with the most recent news we have: 
https://www.guildofstudents.com/news/article/website/Guild-Statement-Confirmation-of-the-reintroduction-of-External-Memberships/

### PR DESCRIPTION
**Pull request by MattyTheHacker**
closes #448

### CODE REVIEW

**Comment by FrozenDude101** [comment]
Looks good to me, I added the missing markdown tag as the header wasn't showing on the page.

**Comment by MattyTheHacker** [comment]
> Looks good to me, I added the missing markdown tag as the header wasn't showing on the page.

epic thanks

**Comment by MattyTheHacker** [comment]
What do people think about separating the "What's the difference" sections into separate boxes? similar to the bits below it

**Comment by FrozenDude101** [comment]
> What do people think about separating the "What's the difference" sections into separate boxes? similar to the bits below it

I think that'd be best, keep it consistent.

**Comment by MattyTheHacker** [comment]
not sure how I feel about the big "what's the difference" header, looks a bit funky

**Comment by MattyTheHacker** [comment]
I also don't like how the top two sections don't have emojis while the bottom two do, but I also don't want to repeat the same ones

**Comment by FrozenDude101** [comment]
> I also don't like how the top two sections don't have emojis while the bottom two do, but I also don't want to repeat the same ones

It might work better if you remove the person emoji, and keep the student and school emojis (but put them on each)

**Comment by MattyTheHacker** [comment]
I think what's bothering me about this at the moment is there being two boxes with the same title, what do people think about merging it into two boxes with headings within the boxes?

**Comment by FrozenDude101** [comment]
I'm not a fan of the incosistent spacing on the left and right.
Imo, same headers are fine when they're sub headers under different main headers

**Comment by MattyTheHacker** [comment]
> I'm not a fan of the incosistent spacing on the left and right. Imo, same headers are fine when they're sub headers under different main headers

It's because I'm fucking around with the boxes dw about it

**Comment by FrozenDude101** [comment]
> > I'm not a fan of the incosistent spacing on the left and right. Imo, same headers are fine when they're sub headers under different main headers
> 
> It's because I'm fucking around with the boxes dw about it

I'm worrying about it so much I can't sleep.
(Go to sleep Matty)

**Comment by MattyTheHacker** [comment]
> > > I'm not a fan of the incosistent spacing on the left and right. Imo, same headers are fine when they're sub headers under different main headers
> > 
> > 
> > It's because I'm fucking around with the boxes dw about it
> (Go to sleep Matty)

IT'S 11PM

**Comment by FrozenDude101** [comment]
> > > > I'm not a fan of the incosistent spacing on the left and right. Imo, same headers are fine when they're sub headers under different main headers
> > > 
> > > It's because I'm fucking around with the boxes dw about it
> >
> > (Go to sleep Matty)
> 
> IT'S 11PM

Time to get a good night's rest.

**Comment by MattyTheHacker** [comment]
review plox

**Pull request merged**
