### PR TITLE
Update Fonts in line with rest of branding

### PR DESCRIPTION
**Pull request by AlexJBanks**
Remove Inconsolata (apart from as backup) and replace with JetBrains Mono.
Replace Noto Sans with Roboto.
Assorted other changes to make fonts appear consistently across the site.

Feedback greatly appreciated

### CODE REVIEW

**Comment by jedevc** [comment]
I quite like the new fonts, as well as the new top bar color. LGTM!

**Comment by Danyc0** [comment]
Changes look good to me. That final merge should probably have been a rebase, but oh well. Happy to merge if others are?

**Review by Danyc0 — APPROVED** [review]
All looks much neater!

**Comment by AlexJBanks** [comment]
@Danyc0 we can squash and merge into `master` if that works better?

**Comment by Danyc0** [comment]
Sure

**Pull request merged**
