### PR TITLE
Add new sponsorship logos to the about page

### PR DESCRIPTION
**Pull request by MattyTheHacker**

### CODE REVIEW

**Comment by MattyTheHacker** [comment]
this isn't quite done yet, still need to get appropriate logos for the companies and awaiting confirmation on some

**Comment by MattyTheHacker** [comment]
I am very much aware this is scuffed as fuck. I'll do it better when I add the other logos on once we've got them confirmed

**Comment by LMBishop** [comment]
Please rebase your branch

**Review by JTWWilson — APPROVED** [review]
Looks good to me. Perhaps a squash might make it a bit neater?

**Comment by MattyTheHacker** [comment]
> Looks good to me. Perhaps a squash might make it a bit neater?

oh yeah definitely is gonna be a squash dw lmao

**Comment by MattyTheHacker** [comment]
> Please rebase your branch

why? is there an issue?

**Comment by LMBishop** [comment]
The prettier check has failed because you created your branch before the codebase was formatted

**Comment by MattyTheHacker** [comment]
> The prettier check has failed because you created your branch before the codebase was formatted

I do believe that is now fixed

**Review by LMBishop — APPROVED** [review]

**Pull request merged**
