### PR TITLE
Add redirect for the games people are bringing to Board Games Night

### PR DESCRIPTION
**Pull request by Danyc0**

### CODE REVIEW

**Comment by MattyTheHacker** [comment]
I don't think there should be a blank line between the other links and this one?
other than that looks fine

**Review by LMBishop — APPROVED** [review]

**Comment by Danyc0** [comment]
> I don't think there should be a blank line between the other links and this one? other than that looks fine

There isn't? Are you maybe misreading the commit diff?

**Comment by MattyTheHacker** [comment]
> Are you maybe misreading the commit diff?

I am indeed. lmao sorry

**Review by MattyTheHacker — APPROVED** [review]

**Comment by Danyc0** [comment]
Hang on though, I could probably fix the newline at the end

**Comment by Danyc0** [comment]
Oh no, wait, the newline is fine, just someone had removed it in the past at some point for some reason

**Pull request merged**
