### PR TITLE
Lmao 😎

### PR DESCRIPTION
**Pull request by FrozenDude101**
imagine caring about how people think about you (I'm sorry everyone, I'm drunk 😎)

### CODE REVIEW

**Comment by JTWWilson** [comment]
Go home honey, you’re drunk x

**Comment by georgejkaye** [comment]
Lmao 😎

**Comment by FrozenDude101** [comment]
Lmao, #skill issue, #lmao, #dont care, #het ebnt 😎

**Review by CarrotManMatt — APPROVED** [review]
Are we deciding that pronouns aren't required? IDM, just curious.

**Comment by CarrotManMatt** [comment]
also no clue why prettier keeps dyeing...

**Comment by FrozenDude101** [comment]
Prettier, smhettier

**Review by MattyTheHacker — CHANGES_REQUESTED** [review]
If you merge this into main with a commit message of lmao I'm going to have an aneurism

**Comment by FrozenDude101** [comment]
L

**Comment by FrozenDude101** [comment]
Just be like new pronouns, not hard.

**Comment by codemicro** [comment]
> If you merge this into main with a commit message of lmao I'm going to have an aneurism

You know you can edit the merge message, right?

**Comment by codemicro** [comment]
> If you merge this into main with a commit message of lmao I'm going to have an aneurism

You know you can edit the merge message, right?

**Review by Thatsmusic99 — CHANGES_REQUESTED** [review]
I felt left out so pretend this has some really useful feedback in it other than i dont know what exactly youre trying to chanve

**Comment by FrozenDude101** [comment]
exit code "1", is there really much point @georgejkaye

**Comment by FrozenDude101** [comment]
please? [Check Prettier has been run](https://github.com/CSSUoB/cssuob.github.io/actions/workflows/check_prettier.yml)

**Comment by MattyTheHacker** [comment]
> > If you merge this into main with a commit message of lmao I'm going to have an aneurism
> 
> You know you can edit the merge message, right?

I do but given the drunken state of certain individuals currently I didn't have high hopes 💀

**Comment by codemicro** [comment]
> > > If you merge this into main with a commit message of lmao I'm going to have an aneurism
> > 
> > 
> > You know you can edit the merge message, right?
> 
> I do but given the drunken state of certain individuals currently I didn't have high hopes skull

You make a very good point

**Review by MattyTheHacker — APPROVED** [review]

**Review by Thatsmusic99 — APPROVED** [review]

**Pull request merged**
