### PR TITLE
Create Newsletter “2023-07-03-looking-back-at-2022-23”

### PR DESCRIPTION
**Pull request by JTWWilson**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by JTWWilson** [comment]
Jesus those images have been destroyed. I'm going to see if I can find higher quality versions

**Review by codemicro — APPROVED** [review]
I'm assuming you proofread it (cause I didn't!), LGTM!

**Comment by JTWWilson** [comment]
Ok now it looks good I think. Have a quick check of the preview to check it looks good on your screen too

**Review by Thatsmusic99 — APPROVED** [review]
LGTM, the preview looks fine from here too!

**Pull request merged**
