### PR TITLE
Add ticket link to FAQ

### PR DESCRIPTION
**Pull request by MattyTheHacker**

### CODE REVIEW

**Review by Thatsmusic99 — CHANGES_REQUESTED** [review]
image
Link does not render

**Comment by MattyTheHacker** [comment]
fucking markdown

**Comment by Thatsmusic99** [comment]
Might have to be using HTML instead, like done a little further down

**Comment by MattyTheHacker** [comment]
sorted

**Review by Thatsmusic99 — APPROVED** [review]

**Pull request merged**
