### PR TITLE
Add /tex page

### PR DESCRIPTION
**Pull request by LMBishop**
Made a TeX page, but I don't know much about the actual origins of the mascot other than what I wrote. Any thoughts before I bother writing the rest of the TeX descriptions?

### CODE REVIEW

**Comment by MattyTheHacker** [comment]
Might be nice to have that TeX's pronouns are they/them on there somewhere?

**Comment by LMBishop** [comment]
Technically I have this which I stole from CSS' Twitter

``

``

Question is whether to actually include it like that lol

**Comment by MattyTheHacker** [comment]
I don't think there's any issue with having that on that page somewhere

**Comment by JTWWilson** [comment]
I think the content is pretty good but I think the formatting could be jazzed up a bit. I'm not keen on the table looking like that, and I reckon we could add a bit more text in different places. Would be nice to have some pictures of the stickers too, there are a couple of great posts from people when they received cards or tickets from CSS that could be included

I'm tempted to approve and say merge this and then raise the improvements as issues?

**Comment by LMBishop** [comment]
How would you suggest formatting it aside from a table or basic list? And what text in which places?

> Would be nice to have some pictures of the stickers too, there are a couple of great posts from people when they received cards or tickets from CSS that could be included

I have no stickers on hand to take pictures of so somebody else will have to do that. I also don't know what you mean by cards or tickets, since I've never seen a physical CSS card or ticket

**Comment by JTWWilson** [comment]
Apologies, I think most of the things I thought of were actually done before your time - we sent out Christmas cards in 2020 with Christmas TeX stickers and a little card and we sent out physical tickets for the 2021 Ball along with Ball TeX stickers.

In terms of formatting, I was thinking that something a little bit more like the /Committee page would be nicer, perhaps alternating which side of the page the TeX art appears on and maybe with a timeline? You did a really nice mock-up of a purple timeline with events either side, something like that might be nice for this?

All that said, I think you need extra information on when they were commissioned etc etc so I'm happy to help add more details

**Comment by JTWWilson** [comment]
We did think when we first came up with the page that we could try and do some sort of Pokédex (PokéTeX?!) formatting which might make it look cool. Something like this per TeX? That's going to take a lot of CSS though so is probably for another PR image

**Comment by LMBishop** [comment]
I think the timeline I created is more suited to an actual timeline (e.g. history of CSS or scheduled events), not this. I like the PokeTeX idea, although from an accessibility standpoint it's not great. 

Maybe we can have something like from the game where the user can select a specific TeX to view and then it will list all details:

**Comment by LMBishop** [comment]
> I offer more insights: The name, TeX, comes when I was once sitting in the Sloman Lounge. I suggested to another committee member that the dinosaur should become a mascot, after its debut appearance at the EPS Trophy 2019*. Ofcourse it needed a name, after workshopping a few suggestions, I came up with TeX. This name stems from 't-rex' as in the dinosaur, but is also a pun on 'TeX' as in the typesetting language. I suggested that we should have a competition to name our new founded mascot, but this idea never materialised. So the name it has just stuck around.

Updated with this info

**Review by MattyTheHacker — CHANGES_REQUESTED** [review]
looks good and tbh can probably be merged now if we want to leave this as a kind of "easter egg" type thing but I would rather have it linked to from somewhere so it's naturally accessible, maybe the about page?

**Comment by MattyTheHacker** [comment]
Is there a TeX logo we can throw at the end of that sentence too? <3

**Review by MattyTheHacker — APPROVED** [review]
looks good

**Pull request merged**
