### PR TITLE
added dark mode

### PR DESCRIPTION
**Pull request by PunugupatiSaikumar**
i have added the dark mode and bright mode button

### CODE REVIEW

**Comment by codemicro** [comment]
Hi there. This commit appears to be effectively empty, plus we're not looking to add a dark mode to our website as it's already in line with our branding.

**Comment by MattyTheHacker** [comment]
> we're not looking to add a dark mode to our website

actually not true

**Comment by codemicro** [comment]
> > we're not looking to add a dark mode to our website
> 
> actually not true

my point still stands

**Comment by MattyTheHacker** [comment]
dude did literally just commit an empty file tho fr

**Pull request closed without merging**
