### PR TITLE
Add sponsorship page

### PR DESCRIPTION
**Pull request by codemicro**

### CODE REVIEW

**Review by MattyTheHacker — CHANGES_REQUESTED** [review]
wait fuck no I broke the prettier

**Comment by Thatsmusic99** [comment]
If it's okay I'll merge this in my own time if approved, I'd like to ensure everything works and reads okay (such as the weird button thing that needs checking)

**Review by MattyTheHacker — APPROVED** [review]
looks good to me

**Comment by MattyTheHacker** [comment]
> If it's okay I'll merge this in my own time if approved, I'd like to ensure everything works and reads okay (such as the weird button thing that needs checking)

I'd suggest reviewing it yourself and requesting changes, that way others don't accidentally merge and you can remove your own review when you're ready and mine will still be there

**Pull request merged**
