### PR TITLE
Committee Update for 2021-22

### PR DESCRIPTION
**Pull request by LikkanChung**

### CODE REVIEW

**Review by AlexJBanks — APPROVED** [review]
ye seems fine to me

**Comment by Danyc0** [comment]
There are a LOT of merges in here, and a whole bunch of commits that have nothing to do with this PR (including a lot from 2020). I think you've ended up with a bunch of stuff about the CV workshop in here from some half-merged local repo or something. To fix this you'll need to do quite a bit of rebasing, or better yet, nuke it and start again. In future i'd probably advise you check the commit log in the PR before raising it to make sure you're only PRing the actual thing you want to PR

**Comment by jedevc** [comment]
Main issue I can see here is that the image files are *way* too large. This makes the committee page take far too long too load. There's a fairly specific reason there's a script there to scale the images correctly, since jekyll can't really do that.

Also all the commits need to be squashed into one (though we can do that on commit merge).

**Review by jedevc — CHANGES_REQUESTED** [review]
Image files need scaling down.

**Comment by LikkanChung** [comment]
Updated Image scaling @jedevc 
Corrected merge history @Danyc0 

Also deleted images which were under `_scripts/assets/...` which should not be there.

**Comment by jedevc** [comment]
looks pretty good now, thanks, i'd missed the files that weren't meant to be there.

confused by the `unknown.png` file - for some reason i get 404 status codes in the browser? for `/common/unknown.png` - think it's probably a bug?

**Review by jedevc — APPROVED** [review]

**Pull request merged**
