### PR TITLE
494: update-sponsor-logos

### PR DESCRIPTION
**Pull request by ChrisDev18**
Added new sponsor photos to `assets/sponsorship` folder. These are all of same size now with transparent backgrounds.
(Kept the original photos in directory to prevent any pages which might use these assets from going wrong, you could delete them if you know it's fine)
Edited `about.md` with the new photos.

### CODE REVIEW

**Comment by Thatsmusic99** [comment]
Just a reminder to committee to not merge this until I reach out to sponsors, thank you <3

**Comment by MattyTheHacker** [comment]
@Thatsmusic99 reminder 👀

**Comment by Thatsmusic99** [comment]
Sorry for the lack of update on this, I've been a bit burned out in general but have been feeling better as of recent with the winter break kicking in. :) 

TTD have approved the logo usage themselves, which generally should satisfy all sponsors' contracts. 

My only concern as of right now is the order of sponsors; TTD is our gold sponsor but at the end, whilst Kainos is our bronze sponsor but at the front. BofA and BNY are both silver and in the right order otherwise. 

Thank you for getting this done regardless!

**Comment by ChrisDev18** [comment]
Hey, just changed the order:

image

As it is a simple 4x4 grid, we could change the layout and styling by adding headings for each tier if we need more distinction between gold, silver and bronze tier sponsors.

**Comment by Thatsmusic99** [comment]
It's been a bit slow on my end, but it all looks good from here!

We've since updated our sponsor page with logos, I presume there'd be no issues with differing logos unless other committee disagree.

**Review by MattyTheHacker — APPROVED** [review]

**Pull request merged**
