### PR TITLE
Update committee roles

### PR DESCRIPTION
**Pull request by sapphyree**

### CODE REVIEW

**Review by Danyc0 — COMMENTED** [review]
Personally I prefer just deleting the line instead of commenting it out if using version control. If it's needed later it can just be pulled from the history. Any particular reason why you decided to comment it out instead of delete? I'm not too fussed, so if there's a reason I'll happily merge

**Comment by sapphyree** [comment]
If you take a look at the previous commitee yamls, they all have the postfix and prefix commented out instead of deleted. I thought I'd just follow convention in this case.

**Comment by AlexJBanks** [comment]
I'm happy with it, as we'll have prefix elect in future, but won't authorise unless we're all happy

**Comment by Danyc0** [comment]
Sounds good to me! Will merge

**Review by Danyc0 — APPROVED** [review]

**Pull request merged**
