### PR TITLE
Fix Prettier run and overly permissive regex check

### PR DESCRIPTION
**Pull request by Thatsmusic99**
real shot in the dark but I ran the file through Prettier itself and it seemed suddenly upset about commas missing

### CODE REVIEW

**Review by MattyTheHacker — DISMISSED** [review]
epic

**Comment by Thatsmusic99** [comment]
no way it worked

**Review by MattyTheHacker — APPROVED** [review]
looks good to me

**Review by MattyTheHacker — CHANGES_REQUESTED** [review]
scuffed 
image

**Comment by MattyTheHacker** [comment]
though saying that it looks like it's also partially scuffed in prod already as well
image

**Comment by CarrotManMatt** [comment]
Why did this get closed if there are still issues with prettier running? Are those issues going to be fixed in #441?

**Comment by Thatsmusic99** [comment]
Prettier is to be fixed in #441, the regex issues I'm resolving in a separate PR (which I believe I can get opened soon)

**Pull request closed without merging**
