### PR TITLE
Fix committee archive appearing in wrong order

### LINKED ISSUE #242: Committee Archive appears in the wrong order
From bottom to top, it goes 2020/2021, 2021/2022, then 2019/2020

### PR DESCRIPTION
**Pull request by LMBishop**
Closes #242

### CODE REVIEW

**Comment by rainestormee** [comment]
Would it make sense to have newer committees first then older committees at the bottom of the page?

**Comment by LMBishop** [comment]
Probably, I just followed what I think was intended originally

**Comment by MattyTheHacker** [comment]
> Would it make sense to have newer committees first then older committees at the bottom of the page?

Yeah I think having the newest at the top and oldest at the bottom would be better if possible

**Comment by MattyTheHacker** [comment]
Can we remove the current year from the archive if it's empty? 

image

**Review by MattyTheHacker — APPROVED** [review]
beautiful

**Review by rainestormee — APPROVED** [review]
👍

**Pull request merged**
