### PR TITLE
Improve accessibility

### PR DESCRIPTION
**Pull request by LMBishop**
Front page:

~~Haven't yet been bothered to check or fix any other pages~~

### CODE REVIEW

**Comment by LMBishop** [comment]
Most a11y issues reported by Lighthouse and Axe now are to do with colour, which can't be fixed without deviating away from CSS colours

**Review by MattyTheHacker — APPROVED** [review]
looks good to me

**Comment by rainestormee** [comment]
What’s the coverage like on the whole site? Might be good to update old archived pages if we’re keeping them on here

**Comment by LMBishop** [comment]
I believe most, if not all, of the link-accessible pages are good

**Pull request merged**
