### PR TITLE
Add bbq redirect

### PR DESCRIPTION
**Pull request by qPalee**
Added bbq redirect to buy tickets

### CODE REVIEW

**Review by Thatsmusic99 — COMMENTED** [review]
Some of the changes here, e.g. the meetings file, are out of scope of the PR - preferably it'd just be the links file being changed here.

**Comment by qPalee** [comment]
none of it has actually been changed, when i made a new branch it just copied it all over for some reason and i have since reverted all the accidental changed in this pr

**Comment by Thatsmusic99** [comment]
There's still some files changed beyond the PR scope - but I have only noticed one minor change in the formatting of one of the agenda documents so can probably let it slide. Generally to avoid this I pull before creating a new branch so that branch will also be up to date :) 

For some reason, I'm not having much luck getting the redirect to work, there's some other redirects in there as well that just don't work either but a lot are older (e.g. SloLAN, ducks). Redirects seem to work up to `/git/guestbook`, but stop working afterwords - could it be with recent dependency updates?

**Comment by Thatsmusic99** [comment]
oh i see now oops

Might need to close this PR unfortunately, the wrong file was edited - this is the file used for redirects now, as far as I'm aware: https://github.com/CSSUoB/cssuob.github.io/blob/main/_site/_redirects 

I'll open a separate issue regarding documentation on that.

**Comment by qPalee** [comment]
yeah thats fine we should probably delete this pr, also is it worth deleting this file or is it still required to work?

**Comment by Thatsmusic99** [comment]
I'd say leave it be for now - not sure what deleting it could have an impact on.

**Pull request closed without merging**
