### PR TITLE
Add Guild's fuck up to ticket info

### PR DESCRIPTION
**Pull request by LMBishop**
Why is the guild the way it is

### CODE REVIEW

**Comment by LMBishop** [comment]
Click this button mr charlie 
image

**Comment by MattyTheHacker** [comment]
can we make the text red?

**Review by CharlesESW — APPROVED** [review]
Yeah it looks good I found the button to do this as well

**Review by CharlesESW — APPROVED** [review]
I like the colour change

**Review by MattyTheHacker — APPROVED** [review]
yeah that's good

**Pull request merged**
