### PR TITLE
Use larger images for committee profiles

### PR DESCRIPTION
**Pull request by codemicro**
This is a potential fix to #428 that increases the resolution of the images outputted by the minify script to make them look better on the site. Rationale is explained in [this comment](https://github.com/CSSUoB/cssuob.github.io/issues/428#issuecomment-1605401171).

Refs #417

### CODE REVIEW

**Review by LMBishop — COMMENTED** [review]
Requested review from new code owners

**Review by MattyTheHacker — APPROVED** [review]
Longer term we can look into doing something more complex with serving images but yeah this looks good

**Review by Thatsmusic99 — APPROVED** [review]
LGTM, did think the current committee photos were quite low in resolution. These look a lot better :D 

image

(RIP Ellie's photo though, seems to be botched on the update committee branch too though, I presume that just needs fixing there?)

**Comment by MattyTheHacker** [comment]
All the pics look fine for me on the other PR? Can't check again now for this one and there isn't a deploy preview but maybe check you're up to date?

**Pull request merged**
