### PR TITLE
Hide banner temporarily

### PR DESCRIPTION
**Pull request by AlexJBanks**
retain code for future use

### CODE REVIEW

**Review by JTWWilson — APPROVED** [review]

**Review by Danyc0 — CHANGES_REQUESTED** [review]
In general the idea of leaving code in "in case we need it later" is pretty bad practice when using version control. It just leaves clutter and damages readability for future maintainers. When using version control it's unnecessary because the changes can just be pulled out of the history if required.

I guess I'm happy to be overruled on this if necessary

**Comment by JTWWilson** [comment]
Very good point and one I hadn't thought about. Perhaps we raise an issue reminding us to add this in again ~August 2022?

**Comment by AlexJBanks** [comment]
@Danyc0 This isn't meant to be a "in case we need it later", it's meant to be a "we **will** use this later". I need to clean up the actual way that it's hidden - i.e. check if text exists and only if it does display the banner, but I don't have time to do that now and have added it to #153

**Comment by Danyc0** [comment]
I really don't like the idea that the code is there, and is actually transmitted and can be seen in the source, but just isn't displayed. That's so messy and wasteful.
I completely agree though that the banner needs to go, so I'll approve and merge this now, with a note in #153 that it needs cleaning up

**Review by Danyc0 — APPROVED** [review]

**Pull request merged**
