### PR TITLE
Update constitution

### PR DESCRIPTION
**Pull request by FrozenDude101**
This PR updates the constitution as specified in the EGM.
Pending guild approval.

### CODE REVIEW

**Comment by codemicro** [comment]
brabft

**Comment by MattyTheHacker** [comment]
This will need to be updated with the new version from the guild

**Comment by codemicro** [comment]
Pending approval by the Guild

**Review by MattyTheHacker — CHANGES_REQUESTED** [review]
The indent on 11.2.2 is wrong 
image

**Comment by codemicro** [comment]
Not to be pernickety but that is the version that got approved :P

**Comment by codemicro** [comment]
Updated, review plx

**Review by MattyTheHacker — APPROVED** [review]

**Pull request merged**
