### PR TITLE
Calendar Content Fixes

### PR DESCRIPTION
**Pull request by Thatsmusic99**
- Removes the overly passive regex check and replaces it with symbols often found in a URL
- Add i and u as valid tags (for formatting)
- Parse the ampersand escape code - it is already a part of the description provided by Google Calendar

### CODE REVIEW

**Review by codemicro — COMMENTED** [review]
the number of PRs here pains me 👍

**Review by codemicro — DISMISSED** [review]
that was meant to be an approval you dickhead website

**Review by codemicro — DISMISSED** [review]

**Review by MattyTheHacker — CHANGES_REQUESTED** [review]
it broke prettier again :(

**Review by MattyTheHacker — APPROVED** [review]
beautiful. all is well in the world.

**Pull request merged**
